version: "3"
services:
  redis6:
    image: redis:6.2
    container_name: "redis6"
    privileged: true
    volumes:
      - ./docker/redis6-data:/data
      - ./docker/redis6-conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis6-logs:/logs
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
    ports:
      - "63790:6379"
    environment:
      - TZ="Asia/Shanghai"
  mysql8:
    image: mysql:8.0
#    restart: always
    container_name: "mysql8"
    environment:
      MYSQL_ROOT_PASSWORD: Pass_123
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "33060:3306"
    volumes:
      - ./docker/mysql8-data:/var/lib/mysql
      - ./docker/mysql8-conf:/etc/mysql/conf.d
      - ./docker/mysql8-logs:/logs
  consul:
    # data 没有挂载到外面
    image: "consul:latest"
    container_name: "consul"
    command: ["agent", "-server", "-bootstrap", "-ui", "-node", "1", "-client", "0.0.0.0"]
#    restart: "always"
    ports:
      - "8500:8500"
  zipkin:
    image: "openzipkin/zipkin:latest"
    container_name: "zipkin"
    #    restart: "always"
    ports:
      - "9411:9411"
#    environment:
#      - TZ=Asia/Shanghai
#      - STORAGE_TYPE=mysql
#      - MYSQL_HOST=mysql8
#      - MYSQL_TCP_PORT=3306
#      - MYSQL_DB=zipkin
#      - MYSQL_USER=zipkin
#      - MYSQL_PASS=xxxxxx
#      - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
  server:
    build: ./src/server/
    volumes:
      - ./src/server:/data/project/server
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 9502
      - 9503
      - 9504
    container_name: "server"
    # restart: "always"
    links:
      - consul
      - zipkin
      - mysql8
      - redis6
  client:
    build: ./src/client/
    volumes:
      - ./src/client:/data/project/client
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "9501:9501"
    container_name: "client"
    # restart: "always"
    links:
      - consul
      - zipkin
      - server
      - mysql8
      - redis6
